require:
  - rubocop-rspec
  - rubocop-rails
 #- anycable/rails/compatibility/rubocop

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  # TODO: re-enable
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Metrics/LineLength:
  Enabled: false
  Max: 180

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 30
  ExcludedMethods: [context, describe, feature, scenario, factory, define]

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/PercentLiteralDelimiters:
  # Specify the default preferred delimiter for all types with the 'default' key
  # Override individual delimiters (even with default specified) by specifying
  # an individual key
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Bundler/OrderedGems:
  Enabled: false

Naming/FileName:
  Enabled: false

Capybara/FeatureMethods:
  EnabledMethods: [feature, scenario, xscenario]

RSpec/MultipleExpectations:
  Max: 23

RSpec/ExampleLength:
  Max: 36

RSpec/NestedGroups:
  Max: 5

RSpec/LeadingSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - spec/**/*.rb

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - sandbox
    - production
